language: python
cache: pip
sudo: false
env:
  - PIPENV_VENV_IN_PROJECT=true
python:
  - 3.7
  - 3.8
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - pipenv run test