language: python
cache: pip
sudo: false
python:
  - 3.6
before_install:
  - pip install coverage==4.3 codeclimate-test-reporter
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
script: make coverage
after_success:
  - codeclimate-test-reporter